language: ruby
sudo: false
before_install:
  - gem install bundler -v 1.11.2
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.1.8
    gemfile: gemfiles/rails_5.0.gemfile
